resource/mbas2020-prod/sidebarMetadata.json, resource/mbas2020-test/sidebarMetadata.json
Screenshot of result:
We may need to account for the " I am not a part of the above communities" option in our code-base but that's not a matter we can deal with here I think.
=> Additions to attendee sidebar metadata.

resource/mbas2020-prod/profileMetadataDetails.json, resource/mbas2020-test/profileMetadataDetails.json
Adding in First & Last name visibility, Country of Business and additional sendToCalender opt ins.
=> New Fields and Opt Ins per MBAS requirements.

resource/mbas2020-prod/session_map.json, resource/mbas2020-test/session_map.json
Corrected Session Type Name for Executive Track
=> "Executive Session" -> "Executive Track"

resource/build2020-test/session_map.json
Use the relevant session types from the test data that we are currently using from EventPoint
=> Update build2020 test session map from available test data

resource/inspire2020-prod/sidebarMetadata.json, resource/inspire2020-test/sidebarMetadata.json
@nelson-w PR for session topics
=> Enabling nesting of session topic metadata

resource/ces2020-prod/sidebarMetadata.json, resource/ces2020-test/sidebarMetadata.json
- Remove unnecessary attendee sidebar info
- Add interests to attendee sidebar
=> Update attendee sidebar info

resource/ces2020-prod/session_map.json
=> Made Media Day sessions visible to all (timed release)

resource/ignite2021-test/sidebarMetadata.json
Same changes for Featured Partners Meta Tags on Featured Partners Details page made in TEST copied to PROD
=> Sponsor Meta Tags on Featured Partners Details page

resource/envision2020-prod/sidebarMetadata.json, resource/envision2020-test/sidebarMetadata.json
=> Metadata updates for envision2020

resource/build2021-prod/sidebarMetadata.json, resource/build2021-test/sidebarMetadata.json
Updated github rules for build to show correct tags
=> Updated github rules for build to show correct tags

resource/build2021-prod/sidebarMetadata.json, resource/build2021-test/sidebarMetadata.json, resource/mbas2021-test/sidebarMetadata.json
Add missing session tags and update titles to translate strings
=> Add missing session tags and update titles to translate strings

resource/ready2021-prod/rules.json, resource/ready2021-prod/session_map.json, resource/ready2021-test/rules.json, resource/ready2021-test/session_map.json
and platinum club session sets
=> Update session maps and rules to accommodate new attendee types

resource/ready2021-prod/rules.json, resource/ready2021-test/rules.json
Reverts TeamIntergen/ignite#157
=> Revert "Update Crew/Staff to Crew for ready2021"

resource/ready2021-prod/sidebarMetadata.json, resource/ready2021-test/sidebarMetadata.json
Use translate keys for title; add track, region, connectionZone, and learningZone to, and remove "role" from, Ready2021 session tags
=> Edit Ready2021 session tags

resource/envision2021-prod/rules.json, resource/envision2021-prod/session_map.json, resource/envision2021-test/rules.json, resource/envision2021-test/session_map.json
Reverts TeamIntergen/ignite#177
=> Revert "Update Envision Session Permissions"

resource/ces2020-prod/rules.json
Reverts TeamIntergen/ignite#185
=> Revert "Update attendee map for CEO"

resource/ignite2021nov-prod/session_map.json, resource/ignite2021nov-test/session_map.json
Reverts TeamIntergen/ignite#194
=> Revert "update core theme sessions again for ignite"

resource/together2022-prod/rules.json, resource/together2022-test/rules.json
Got given incorrect attendee types prior to PDC going live.
=> Removing hypens from attendee types in Together prod & test

resource/mcaps2022-prod/session_map.json
Part of the fix for https://dev.azure.com/msesc/DigitalVenue/_workitems/edit/10751/
=> add session scheduler set to MCAPS 2022 Prod

resource/mcaps2022-prod/session_map.json, resource/mcaps2022-test/session_map.json
=> Add studio session type mcaps
